<?php

/**
 * Implements hook_requirements().
 */
function address_requirements($phase) {
  $requirements = array();

  if ($phase == 'install') {
    if (!class_exists('\CommerceGuys\Addressing\Repository\AddressFormatRepository')) {
      $requirements['addressing_library'] = array(
        'description' => t('Address requires the commerceguys/addressing library.'),
        'severity' => REQUIREMENT_ERROR,
      );
    }
  }

  return $requirements;
}
